<?php

/**
 * @file
 * Provide a scrolling items display style for Views.
 */


/**
 * Implements hook_help().
 */
function views_ticker_help($path, $arg) {
  switch ($path) {
    default:
      $output = "";
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function views_ticker_theme() {
  return array(
    'views_ticker' => array(
      'variables' => array('items' => NULL, 'options' => NULL, 'identifier' => NULL),
    ),
  );
}


/**
 * Implements hook_views_api().
 */
function views_ticker_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_ticker') . '/includes',
  );
}

/**
 * Implements hook_autoload_info().
 */
function views_ticker_autoload_info() {
  return array(
    'views_ticker_style_plugin' => 'includes/views_ticker_style_plugin.inc',
  );
}
